minimum_pre_commit_version: "2.17"

default_language_version:
  python: python3

fail_fast: false

repos:
  - repo: local
    hooks:
      - id: clang-format
        name: clang-format
        entry: clang-format -i
        args: ["-fallback-style=none"]
        language: python
        files: |
          (?x)(
              ^src/.*
            )$